[versions]
activityCompose = "1.9.2"
androidGradlePlugin = "8.6.0"
browserVersion = "1.8.0"
coilVersion = "2.7.0"
composeBom = "2024.09.01"
coreVersion = "1.13.1"
epoxyVersion = "5.1.4"
espressoVersion = "3.6.1"
gplayapiVersion = "3.4.1"
gsonVersion = "2.11.0"
hiddenapibypassVersion = "4.3"
hiltVersion = "2.52"
hiltWorkVersion = "1.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinVersion = "2.0.20"
kspVersion = "2.0.20-1.0.24"
ktlintVersion = "12.1.1"
leakcanaryAndroidVersion = "2.14"
libsu = "6.0.0"
lifeVersion = "2.8.5"
materialVersion = "1.12.0"
navVersion = "2.8.0"
okhttpVersion = "4.12.0"
preferenceVersion = "1.2.1"
protobufJavaliteVersion = "4.28.0"
rikkaHiddenVersion = "4.3.3"
rikkaToolsVersion = "4.4.0"
roomVersion = "2.6.1"
shimmerVersion = "0.5.0"
shizukuVersion = "13.1.5"
swiperefreshlayoutVersion = "1.1.0"
truth = "1.4.4"
viewpager2Version = "1.1.0"
workVersion = "2.9.1"

[libraries]
airbnb-epoxy-android = { module = "com.airbnb.android:epoxy", version.ref = "epoxyVersion" }
airbnb-epoxy-processor = { module = "com.airbnb.android:epoxy-processor", version.ref = "epoxyVersion" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browserVersion" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreVersion" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion" }
androidx-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "junitVersion" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifeVersion" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifeVersion" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayoutVersion" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2Version" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workVersion" }
auroraoss-gplayapi = { module = "com.auroraoss:gplayapi", version.ref = "gplayapiVersion" }
coil-kt = { module = "io.coil-kt:coil", version.ref = "coilVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmerVersion" }
github-topjohnwu-libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
google-android-material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
google-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavaliteVersion" }
google-truth = { module = "com.google.truth:truth", version.ref = "truth" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
hilt-android-core = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltVersion" }
hilt-androidx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWorkVersion" }
hilt-androidx-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
lsposed-hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypassVersion" }
rikka-hidden-stub = { module = "dev.rikka.hidden:stub", version.ref = "rikkaHiddenVersion" }
rikka-shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizukuVersion" }
rikka-shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizukuVersion" }
rikka-tools-refine-runtime = { module = "dev.rikka.tools.refine:runtime", version.ref = "rikkaToolsVersion" }
squareup-leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroidVersion" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidx-navigation  = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navVersion" }
google-ksp  = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
hilt-android-plugin  = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
ktlint  = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintVersion" }
jetbrains-kotlin-android  = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
jetbrains-kotlin-parcelize  = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinVersion" }
rikka-tools-refine-plugin  = { id = "dev.rikka.tools.refine", version.ref = "rikkaToolsVersion" }
